spring.application.name=backEnd
	spring.datasource.driver=org.postgresql.Driver
	spring.datasource.url=jdbc:postgresql://dpg-d931fmmrnols7384a2ig-a.oregon-postgres.render.com:5432/academico_9z3m
	spring.datasource.username=postgress
	spring.datasource.password=oYGjZMXKdBhsc7CfXFAs4rr2e8wHxJWR
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

media.location=mediafiless
server.address=0.0.0.0

server.port=8080

# Hibernate no imprime errores de constraint / SQL en consola
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=OFF
